// Vue/Vue-admin-template/vue-admin/src/App.vue
<!--
 * @Author: GZH
 * @Date: 2021-11-01 10:02:12
 * @LastEditors: GZH
 * @LastEditTime: 2021-11-03 13:46:32
 * @FilePath: \vue-admin\src\App.vue
 * @Description: 
-->
<script setup lang="ts">
// import Comp from '@/components/Count.vue'
</script>

<template>
    <!-- <Comp msg="测试msg" /> -->
    <router-view></router-view>
</template>

<style scoped lang="scss"></style>

// React/1-react-components/src/App.js
/*
 * @Author: GZH
 * @Date: 2021-09-22 19:51:51
 * @LastEditors: GZH
 * @LastEditTime: 2021-09-23 20:11:39
 * @FilePath: \rewrite\React\1-react-components\src\App.js
 * @Description:
 */
import React from 'react';
// import ContextPage from "./pages/ContextPage";
// import HocPage from "./pages/HocPage";
// import AntdFormPage from "./pages/AntdFormPage";
import MyRCFieldForm from './pages/MyRCFieldForm';
// import MyRCForm from './pages/MyRCForm';
// import DialogPage from './pages/DialogPage';

export default function App(props) {
  return (
    <div>
      {/* <ContextPage /> */}
      {/* <HocPage /> */}
      {/* <AntdFormPage /> */}
      <MyRCFieldForm />
      {/* <MyRCForm /> */}
      {/* <DialogPage /> */}
    </div>
  );
}
