// Vue/Vue-admin-template/vue-admin-ts/src/App.vue
<!--
 * @Author: GZH
 * @Date: 2021-11-09 16:29:11
 * @LastEditors: GZH
 * @LastEditTime: 2021-11-10 15:03:56
 * @FilePath: \vue-admin-ts\src\App.vue
 * @Description: 
-->
<template>
    <router-view></router-view>
</template>

<script setup lang="ts"></script>
<style>
html,
body {
    padding: 0;
    margin: 0;
}
</style>

// React/1-react-components/src/App.js
/*
 * @Author: GZH
 * @Date: 2021-09-22 19:51:51
 * @LastEditors: GZH
 * @LastEditTime: 2021-09-23 20:11:39
 * @FilePath: \rewrite\React\1-react-components\src\App.js
 * @Description:
 */
import React from 'react';
// import ContextPage from "./pages/ContextPage";
// import HocPage from "./pages/HocPage";
// import AntdFormPage from "./pages/AntdFormPage";
import MyRCFieldForm from './pages/MyRCFieldForm';
// import MyRCForm from './pages/MyRCForm';
// import DialogPage from './pages/DialogPage';

export default function App(props) {
  return (
    <div>
      {/* <ContextPage /> */}
      {/* <HocPage /> */}
      {/* <AntdFormPage /> */}
      <MyRCFieldForm />
      {/* <MyRCForm /> */}
      {/* <DialogPage /> */}
    </div>
  );
}
